CONNECT qstadmin/&qstadmin_pwd@&&instance

DROP TABLE QSTADMIN.QST_ZUORA_SALES_CREDITS CASCADE CONSTRAINTS;

CREATE TABLE QSTADMIN.QST_ZUORA_SALES_CREDITS
(
  ZQUOTE_RECORD_ID       VARCHAR2(500 BYTE),
  ZUORA_INVOICE_NUM      VARCHAR2(500 BYTE),
  ZUORA_SUBSCRIPTION_ID  VARCHAR2(240 BYTE),
  SALESREP_ID            NUMBER,
  SALESREP_NUMBER        VARCHAR2(500 BYTE),
  SALES_CREDIT_TYPE      VARCHAR2(500 BYTE),
  SALES_CREDIT_TYPE_ID   NUMBER,
  PERCENT                NUMBER,
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATED_DATE      DATE,
  LAST_UPDATED_BY        NUMBER,
  REQUEST_ID             NUMBER,
  ERROR_MESSAGE          VARCHAR2(4000 BYTE),
  STATUS_FLAG            VARCHAR2(1 BYTE),
  ATTRIBUTE1             VARCHAR2(500 BYTE),
  ATTRIBUTE2             VARCHAR2(500 BYTE),
  ATTRIBUTE3             VARCHAR2(500 BYTE),
  ATTRIBUTE4             VARCHAR2(500 BYTE),
  ATTRIBUTE5             VARCHAR2(500 BYTE),
  ATTRIBUTE6             VARCHAR2(500 BYTE),
  ATTRIBUTE7             VARCHAR2(500 BYTE),
  ATTRIBUTE8             VARCHAR2(500 BYTE),
  ATTRIBUTE9             VARCHAR2(500 BYTE),
  ATTRIBUTE10            VARCHAR2(500 BYTE),
  ATTRIBUTE11            VARCHAR2(500 BYTE),
  ATTRIBUTE12            VARCHAR2(500 BYTE),
  ATTRIBUTE13            VARCHAR2(500 BYTE),
  ATTRIBUTE14            VARCHAR2(500 BYTE),
  ATTRIBUTE15            VARCHAR2(500 BYTE)
);

GRANT ALL ON QST_ZUORA_SALES_CREDITS TO APPS;


CONNECT apps/&apps_pwd@&&instance

DROP SYNONYM APPS.QST_ZUORA_SALES_CREDITS;

CREATE SYNONYM APPS.QST_ZUORA_SALES_CREDITS FOR QSTADMIN.QST_ZUORA_SALES_CREDITS;
