Connect QSTADMIN/&&QSTADMIN_pwd@&&instance

DROP TABLE QSTADMIN.QST_ZUORA_PAYMENTS_STG CASCADE CONSTRAINTS;

CREATE TABLE QSTADMIN.QST_ZUORA_PAYMENTS_STG
(
  RECORD_ID            NUMBER,
  STATUS_FLAG          VARCHAR2(1 BYTE),
  ERROR_MESSAGE        VARCHAR2(4000 BYTE),
  REQUEST_ID           NUMBER,
  CUST_ACCOUNT_ID      NUMBER,
  CUSTOMER_NAME        VARCHAR2(500 BYTE),
  ACCOUNT_NUMBER       VARCHAR2(500 BYTE),
  AMOUNT               NUMBER,
  APPLIED_INV_AMOUNT   NUMBER,
  RECEIPT_DATE         DATE,
  INVOICE_NUMBER       VARCHAR2(500 BYTE),
  RECEIPT_NUMBER       VARCHAR2(500 BYTE),
  CREATION_DATE        DATE,
  CREATED_BY           NUMBER,
  LAST_UPDATED_DATE    DATE,
  LAST_UPDATED_BY      NUMBER,
  Z_INVOICE_NUM        VARCHAR2(500 BYTE),
  Z_PAYMENT_METHOD_ID  VARCHAR2(500 BYTE),
  Z_ACCOUNT_ID         VARCHAR2(500 BYTE),
  STATUS               VARCHAR2(500 BYTE),
  TYPE                 VARCHAR2(500 BYTE),
  REFERENCE_ID         VARCHAR2(500 BYTE),
  CASH_RECEIPT_ID      NUMBER,
  CUSTOMER_TRX_ID      NUMBER,
  ORG_ID               NUMBER,
  Z_PAYMENT_NUM        VARCHAR2(4000 BYTE),
  ATTRIBUTE1           VARCHAR2(4000 BYTE),
  ATTRIBUTE2           VARCHAR2(4000 BYTE),
  ATTRIBUTE3           VARCHAR2(4000 BYTE),
  ATTRIBUTE4           VARCHAR2(4000 BYTE),
  ATTRIBUTE5           VARCHAR2(4000 BYTE),
  ATTRIBUTE6           VARCHAR2(4000 BYTE),
  ATTRIBUTE7           VARCHAR2(4000 BYTE),
  ATTRIBUTE8           VARCHAR2(4000 BYTE),
  ATTRIBUTE9           VARCHAR2(4000 BYTE),
  ATTRIBUTE10          VARCHAR2(4000 BYTE),
  ATTRIBUTE11          VARCHAR2(4000 BYTE),
  ATTRIBUTE12          VARCHAR2(4000 BYTE),
  ATTRIBUTE13          VARCHAR2(4000 BYTE),
  ATTRIBUTE14          VARCHAR2(4000 BYTE),
  ATTRIBUTE15          VARCHAR2(4000 BYTE),
  ATTRIBUTE16          VARCHAR2(4000 BYTE),
  ATTRIBUTE17          VARCHAR2(4000 BYTE),
  ATTRIBUTE18          VARCHAR2(4000 BYTE),
  ATTRIBUTE19          VARCHAR2(4000 BYTE),
  ATTRIBUTE20          VARCHAR2(4000 BYTE),
  ATTRIBUTE21          VARCHAR2(4000 BYTE),
  ATTRIBUTE22          VARCHAR2(4000 BYTE),
  ATTRIBUTE23          VARCHAR2(4000 BYTE),
  ATTRIBUTE24          VARCHAR2(4000 BYTE),
  ATTRIBUTE25          VARCHAR2(4000 BYTE),
  ATTRIBUTE26          VARCHAR2(4000 BYTE),
  ATTRIBUTE27          VARCHAR2(4000 BYTE),
  ATTRIBUTE28          VARCHAR2(4000 BYTE),
  ATTRIBUTE29          VARCHAR2(4000 BYTE),
  ATTRIBUTE30          VARCHAR2(4000 BYTE)
);


GRANT ALL ON QST_ZUORA_PAYMENTS_STG to APPS;

DROP SEQUENCE QSTADMIN.QST_ZUORA_PAYMENTS_STG_S;

CREATE SEQUENCE QSTADMIN.QST_ZUORA_PAYMENTS_STG_S
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

GRANT ALL ON QST_ZUORA_PAYMENTS_STG_S to APPS;
  
Connect apps/&&apps_pwd@&&instance

DROP SYNONYM APPS.QST_ZUORA_PAYMENTS_STG;

CREATE SYNONYM APPS.QST_ZUORA_PAYMENTS_STG FOR QSTADMIN.QST_ZUORA_PAYMENTS_STG;

DROP SYNONYM APPS.QST_ZUORA_PAYMENTS_STG_S;

CREATE SYNONYM APPS.QST_ZUORA_PAYMENTS_STG_S FOR QSTADMIN.QST_ZUORA_PAYMENTS_STG_S;
