Connect QSTADMIN/&QSTADMIN_pwd@&&instance

ALTER TABLE QSTADMIN.QST_ZUORA_INVOICE ADD (BILL_TO_ACCT_ID VARCHAR2(240), SHIP_TO_ACCT_ID VARCHAR2(240));

--==============
CREATE INDEX QSTADMIN.QST_ZUORA_INVOICE_N1 ON QSTADMIN.QST_ZUORA_INVOICE (request_id);

CREATE INDEX QST_ZUORA_INVOICE_N2 ON QSTADMIN.QST_ZUORA_INVOICE (zuora_invoice_num);

CREATE INDEX QST_ZUORA_INVOICE_N3 ON QSTADMIN.QST_ZUORA_INVOICE (nvl(status_flag,'N'));

CREATE INDEX QST_ZUORA_INVOICE_N4 ON QSTADMIN.QST_ZUORA_INVOICE (attribute14,attribute15);


--==============
CREATE INDEX QST_ZUORA_REQUEST_N1 ON QSTADMIN.QST_ZUORA_REQUEST (request_id);

--==============
CREATE INDEX QST_ZUORA_SALES_CREDITS_N1 ON QSTADMIN.QST_ZUORA_SALES_CREDITS (request_id);

CREATE INDEX QST_ZUORA_SALES_CREDITS_N2 ON QSTADMIN.QST_ZUORA_SALES_CREDITS (zuora_invoice_num);

CREATE INDEX QST_ZUORA_SALES_CREDITS_N3 ON QSTADMIN.QST_ZUORA_SALES_CREDITS (request_id,zuora_invoice_num,attribute8);
--==============



--Connect apps/&apps_pwd@&&instance

--DROP SYNONYM APPS.QST_ZUORA_INVOICE;

--CREATE SYNONYM APPS.QST_ZUORA_INVOICE FOR QSTADMIN.QST_ZUORA_INVOICE;

